### PR TITLE
use `url.QueryEscape` to escape some special characters; fix misspel…

### PR DESCRIPTION
**Pull request by Mrliu8023**
### 优化的功能:
- 使用`url.QueryEscape`替换`strings.Replace`方法，支持更多特殊符号。

### 修复的问题：
- mongo_test.go内`dbClient`拼写错误。

### CODE REVIEW

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/bk-cmdb?pullRequest=5230) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/bk-cmdb?pullRequest=5230) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/bk-cmdb?pullRequest=5230) it.</sub>

**Review by rentiansheng — APPROVED** [review]
同意

**Comment by rentiansheng** [comment]
@Mrliu8023  目前的开发分支是在v3.9.x, 麻烦提交v3.9.x

**Comment by Mrliu8023** [comment]
> @Mrliu8023 目前的开发分支是在v3.9.x, 麻烦提交v3.9.x

好的

**Pull request merged**
