### PR TITLE
doc:fix json syntax error in host_relation.md

### PR DESCRIPTION
**Pull request by DeKaiju**

### CODE REVIEW

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/bk-cmdb?pullRequest=1844) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/bk-cmdb?pullRequest=1844) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/bk-cmdb?pullRequest=1844) it.</sub>

**Comment by breezelxp** [comment]
@DeKaiju 感谢你的PR，请签署下社区的CLA协议，链接如下：
https://cla.opensource.tencent.com/Tencent/bk-cmdb?pullRequest=1844

**Comment by DeKaiju** [comment]
的确是在release中的3.2.2的版本发现的，因为我不想签署CLA协议所以决定关掉这个PR

**Comment by breezelxp** [comment]
> 的确是在release中的3.2.2的版本发现的，因为我不想签署CLA协议所以决定关掉这个PR

好的，感谢。

**Pull request closed without merging**
